### ISSUE TITLE
NoRegionError

### ISSUE THREAD

**Issue by yanmi89** [yankevn/stock_analysis#1]
I'm getting a no region error. Someone on AWS posted this and looks like it worked fine on their local computer but once it was on github, this occurred. Is it possible to specify the region in the code? 

Error:
yanmi89@DESKTOP-6E3C2LF:~/eecs280/p1-stats/stock_analysis$ python3 index.py
Traceback (most recent call last):
  File "/home/yanmi89/eecs280/p1-stats/stock_analysis/index.py", line 19, in <module>
    create_tables_if_not_exist()
  File "/home/yanmi89/eecs280/p1-stats/stock_analysis/dynamodb.py", line 18, in create_tables_if_not_exist
    client = get_low_level_db_client()
  File "/home/yanmi89/eecs280/p1-stats/stock_analysis/dynamodb.py", line 72, in get_low_level_db_client
    return boto3.client(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/yanmi89/.local/lib/python3.10/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/client.py", line 508, in _get_client_args
    return args_creator.get_client_args(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/args.py", line 100, in get_client_args
    final_args = self.compute_client_args(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/args.py", line 219, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/args.py", line 369, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/args.py", line 474, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/client.py", line 613, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/home/yanmi89/.local/lib/python3.10/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Comment by yankevn** [comment]
Make sure to follow the [python virtual environment tutorial](https://eecs485staff.github.io/p1-insta485-static/setup_virtual_env.html) first. After you activate you virtual environment and upgrade pip, just run `pip install -r requirements.txt` and then try running the code again.
